export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_SORT_SPIS = 'SET_SORT_SPIS';
export const SET_ROWS_PER_PAGE = 'SET_ROWS_PER_PAGE';
export const SET_SORT_TYPES='SET_SORT_TYPES';
export const SET_SORT_TITLE='SET_SORT_TITLE';
